CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    location VARCHAR(160) NOT NULL,
    manager_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_departments_name_nonblank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_departments_location_nonblank CHECK (length(btrim(location)) > 0),
    CONSTRAINT ck_departments_updated_at_not_before_created_at CHECK (updated_at >= created_at)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(254) NOT NULL,
    role VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    department_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_full_name_nonblank CHECK (length(btrim(full_name)) > 0),
    CONSTRAINT ck_users_email_nonblank CHECK (length(btrim(email)) > 0),
    CONSTRAINT ck_users_role_allowed CHECK (role IN ('ADMIN', 'MANAGER', 'ANALYST', 'ENGINEER', 'OPERATIONS')),
    CONSTRAINT ck_users_status_allowed CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),
    CONSTRAINT ck_users_updated_at_not_before_created_at CHECK (updated_at >= created_at),
    CONSTRAINT fk_users_department
        FOREIGN KEY (department_id)
        REFERENCES departments (id)
        ON DELETE RESTRICT
);

ALTER TABLE departments
    ADD CONSTRAINT fk_departments_manager_user
    FOREIGN KEY (manager_user_id)
    REFERENCES users (id)
    ON DELETE SET NULL;

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    department_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_projects_name_nonblank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_projects_status_allowed CHECK (status IN ('PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_projects_end_date_not_before_start_date CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_projects_updated_at_not_before_created_at CHECK (updated_at >= created_at),
    CONSTRAINT fk_projects_department
        FOREIGN KEY (department_id)
        REFERENCES departments (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_projects_owner_user
        FOREIGN KEY (owner_user_id)
        REFERENCES users (id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ux_departments_name_lower ON departments (lower(name));
CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));

CREATE INDEX ix_departments_manager_user_id ON departments (manager_user_id);
CREATE INDEX ix_users_department_id ON users (department_id);
CREATE INDEX ix_projects_department_id ON projects (department_id);
CREATE INDEX ix_projects_owner_user_id ON projects (owner_user_id);
