spring.application.name=reporting-api

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info
