spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.url=${DB_MIGRATION_URL:${DB_URL}}
spring.flyway.user=${DB_MIGRATION_USERNAME:${DB_USERNAME}}
spring.flyway.password=${DB_MIGRATION_PASSWORD:${DB_PASSWORD}}
