spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/reporting_portal}
spring.datasource.username=${DB_USERNAME:reporting_user}
spring.datasource.password=${DB_PASSWORD:reporting_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.url=${DB_MIGRATION_URL:${spring.datasource.url}}
spring.flyway.user=${DB_MIGRATION_USERNAME:${spring.datasource.username}}
spring.flyway.password=${DB_MIGRATION_PASSWORD:${spring.datasource.password}}
